# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.5

EAPI=8

RUST_MIN_VER="1.89.0"

CRATES="
	approx@0.5.1
	autocfg@1.5.1
	bytemuck@1.25.2
	glam@0.30.10
	glam@0.31.1
	glam@0.32.1
	glam@0.33.12
	lv2-atom@2.0.0
	lv2-core-derive@2.1.1
	lv2-core@3.0.0
	lv2-midi@1.2.0
	lv2-sys@2.0.0
	lv2-units@0.1.3
	lv2-urid@2.1.0
	lv2@0.6.0
	matrixmultiply@0.3.11
	nalgebra-macros@0.3.0
	nalgebra@0.35.0
	num-bigint@0.4.8
	num-complex@0.4.6
	num-integer@0.1.47
	num-rational@0.4.2
	num-traits@0.2.19
	proc-macro2@1.0.107
	quote@1.0.47
	rawpointer@0.2.1
	safe_arch@1.2.0
	simba@0.10.2
	syn@1.0.109
	syn@2.0.119
	typenum@1.20.1
	unicode-ident@1.0.26
	urid-derive@0.1.1
	urid@0.1.0
	wide@1.7.1
	wmidi@3.1.0
"

inherit cargo

DESCRIPTION="Minimum variance distortionless response beamformer for Apple mic arrays"
HOMEPAGE="https://github.com/chadmed/triforce"
SRC_URI="
	https://github.com/chadmed/triforce/archive/refs/tags/${PV}.tar.gz -> ${PN}-${PV}.tar.gz
	${CARGO_CRATE_URIS}
"

S="${WORKDIR}/triforce-${PV}"

LICENSE="GPL-2+"
# Dependent crate licenses
LICENSE+=" Apache-2.0 MIT Unicode-3.0"
SLOT="0"
KEYWORDS="~arm64"

DEPEND="
media-libs/lv2
"
RDEPEND="${DEPEND}"

# cargo.eclass now builds arch-specific targets
src_prepare() {
	sed -i \
		-e "s|target/release|$(cargo_target_dir)|" Makefile || die
	default
}

src_configure() {
	cargo_src_configure
}

src_install() {
	emake DESTDIR="${D}" LIBDIR="/usr/$(get_libdir)" install || die
}
