#!/bin/sh
# SPDX-License-Identifier: MIT

set -e

if [ $(whoami) -ne "root" ]; then
    echo "This script must be run as root"
    exit 1
fi

PREFIX="/boot/efi"
FW_ARCHIVE="asahi/all_firmware.tar.gz"

if [ ! -f ${PREFIX}/${FW_ARCHIVE} ]; then
    printf '==> No /boot/efi/asahi/all_firmware.tar.gz, trying /boot'
    PREFIX="/boot"
    if [ ! -f ${PREFIX}/${FW_ARCHIVE} ]; then
        printf '==> No /boot/asahi/all_firmware.tar.gz. Skipping firmware upgrade.'
        exit 1
    fi
fi

printf '==> Upgrading vendor firmware package...\n'
python -m asahi_firmware.update ${PREFIX}/asahi ${PREFIX}/vendorfw
printf '    Firmware upgraded\n'
