# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.16.0

EAPI=8
RUST_MIN_VER="1.85.0"

CRATES="
	anyhow@1.0.102
	bitflags@2.13.0
	bumpalo@3.20.3
	cfg-if@1.0.4
	crc-catalog@2.5.0
	crc@3.4.0
	futures-core@0.3.32
	futures-task@0.3.32
	futures-util@0.3.32
	getrandom@0.4.3
	gpt@3.1.0
	js-sys@0.3.102
	libc@0.2.186
	log@0.4.33
	once_cell@1.21.4
	pin-project-lite@0.2.17
	proc-macro2@1.0.106
	quote@1.0.45
	r-efi@6.0.0
	rustversion@1.0.22
	slab@0.4.12
	syn@2.0.118
	unicode-ident@1.0.24
	uuid@1.23.3
	wasm-bindgen-macro-support@0.2.125
	wasm-bindgen-macro@0.2.125
	wasm-bindgen-shared@0.2.125
	wasm-bindgen@0.2.125
"

inherit cargo

DESCRIPTION="Fix macOS 27 bootability flag from linux side"
HOMEPAGE="https://github.com/AsahiLinux/asahi-fix27"
SRC_URI="
	${CARGO_CRATE_URIS}
	https://github.com/AsahiLinux/${PN}/archive/refs/tags/${PV}.tar.gz -> ${P}.tar.gz
"

LICENSE="GPL-2"
# Dependent crate licenses
LICENSE+=" MIT Unicode-3.0"
SLOT="0"
KEYWORDS="~arm64"
